language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm install -g grunt-cli

before_script:
  - gem install sass --version 3.4.13
  - grunt